require 'lib/logics/comment_logic'
require 'lib/logics/rating_logic'
require 'lib/logics/voting_logic'
require 'lib/logics/ranking_logic'
require 'string/extender/ctype'
require 'string/extender/html'
require 'patches/typus'
require 'patches/typus_authentication_session'
