# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Spot:
  fields:
    default: name, latitude, longitude, address
    form: name, latitude, longitude, address, annotation
  order_by: 
  relationships:
  filters: 
  search: name
  application: tabiplus

Plan:
  fields:
    default: user_id, title, status, public, owner
    form: user_id, title, status, outline, public, owner
  order_by: 
  relationships: destinations
  filters: 
  search: title
  application: tabiplus

Destination:
  fields:
    default: position, plan_id, spot_id, time, spot, plan
    form: plan_id, spot_id, comment, time, spot, plan
  order_by: position
  relationships: plan, spot
  filters: 
  search: 
  application: tabiplus

News:
  fields:
    default: title, published_at
    form: title, body, published_at
  order_by:
  relationships:
  filters:
  search: title
  application: tabiplus

Comment:
  fields:
    default: commenter_id, commentable_id, body, commenter
    form: commenter_id, commentable_id, body, commenter
  order_by:
  relationships: commenter
  filters:
  search:
  application: tabiplus

DestinationPhoto:
  fields:
    default: destination_id, photo_id, destination, photo
    form: destination_id, photo_id, destination, photo
  order_by:
  relationships: destination, photo
  filters:
  search:
  application: tabiplus

Ranking:
  fields:
    default: rankable_id, point, range
    form: rankable_id, point, range
  order_by:
  relationships:
  filters:
  search:
  application: tabiplus

Rating:
  fields:
    default: user_id, ratable_id, score, dimension, user
    form: user_id, ratable_id, score, dimension, user
  order_by:
  relationships: user
  filters:
  search:
  application: tabiplus

SiteConfig:
  fields:
    default: name
    form: name, value, comment
  order_by:
  relationships:
  filters:
  search: name
  application: tabiplus

SpotPhoto:
  fields:
    default: user_id, spot_id, photo_file_name, spot, user
    form: user_id, spot_id, photo_file_name, spot, user
  order_by:
  relationships: spot, user
  filters:
  search:
  application: tabiplus

User:
  fields:
    default: twitter_id, login, access_token, access_secret, remember_token, remember_token_expires_at, name, location, description, profile_image_url, url, protected, profile_background_color, profile_sidebar_fill_color, profile_link_color, profile_sidebar_border_color, profile_text_color, profile_background_image_url, profile_background_tile, friends_count, statuses_count, followers_count, favourites_count, utc_offset, time_zone
    form: twitter_id, login, access_token, access_secret, remember_token, remember_token_expires_at, name, location, description, profile_image_url, url, protected, profile_background_color, profile_sidebar_fill_color, profile_link_color, profile_sidebar_border_color, profile_text_color, profile_background_image_url, profile_background_tile, friends_count, statuses_count, followers_count, favourites_count, utc_offset, time_zone
  order_by:
  relationships: photos, plans, rankings
  filters:
  search: name
  application: tabiplus

Voting:
  fields:
    default: user_id, votable_id, dimension, user
    form: user_id, votable_id, dimension, user
  order_by:
  relationships: user
  filters:
  search:
  application: tabiplus
